name: Push Event workflow

on: push

jobs:
    unit_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Package
      uses: pip install pytest

    - name: Run Tests
      uses: pytest test.py
